trigger:
  - main

pool:
  name: dev-pipeline-agent

variables:
  imageName: 'medicalwebsite'

steps:
- task: Docker@2
  displayName: 'Login to ACR'
  inputs:
    command: login
    containerRegistry: 'medicalwebsite-acr'  # Service connection name (create this in Azure DevOps)

- task: Docker@2
  displayName: 'Build and Push Docker Image'
  inputs:
    command: buildAndPush
    repository: $(imageName)
    dockerfile: '**/Dockerfile'
    tags: |
      latest

- task: AzureWebAppContainer@1
  displayName: 'Deploy to App Service'
  inputs:
    azureSubscription: 'medicalwebsite-sub'   # Azure DevOps service connection
    appName: 'medical-store'                  # Your App Service name
    containers: 'medicalwebsite.azurecr.io/$(imageName):latest'
