trigger:
  branches:
    include:
      - master

pool:
  name: dev-pipeline-agent

variables:
  imageName: 'medicalwebsite'

stages:
- stage: BuildAndPush
  displayName: Build and Push Docker Image
  jobs:
  - job: DockerBuildPush
    steps:
    - task: Docker@2
      displayName: Build and Push Image to ACR (medicalwebsite)
      inputs:
        containerRegistry: 'pharmacy-acr'  # ✅ Docker-compatible service connection
        repository: 'medicalwebsite'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'        # Adjust if your Dockerfile is deeper
        tags: |
          latest

- stage: Deploy
  displayName: Deploy to Azure Web App
  dependsOn: BuildAndPush
  jobs:
  - job: WebAppDeploy
    steps:
    - task: AzureWebAppContainer@1
      displayName: Deploy to App Service
      inputs:
        azureSubscription: 'azure-service-connection-dev'  # ✅ Azure Resource Manager
        appName: 'medical-store'                           # Your Web App name
        containers: 'medicalwebsite.azurecr.io/medicalwebsite:latest'
