trigger:
- master

pool:
  name: Default                  # ✅ Matches your Azure DevOps pool name
  demands:
    - agent.name -equals dev-pipeline-agent  # ✅ Must match the exact agent name

steps:
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/output.zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/output.zip'
    ArtifactName: 'drop'
    publishLocation: 'Container'
