name: Build and Push to ECR

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  AWS_REGION: ap-south-1
  ECR_REPOSITORY: frontend-k8s-test
  IMAGE_TAG: latest

jobs:
  build-and-push:
    name: Build and Push Docker image to ECR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Extract repo URI
        id: ecr
        run: |
          echo "REPO_URI=${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}" >> $GITHUB_ENV

      - name: Generate image tag with timestamp
        id: vars
        run: |
          TIMESTAMP=$(date +'%Y-%m-%d-%H-%M-%S')
          echo "IMAGE_TAG_WITH_DATE=${TIMESTAMP}" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t $REPO_URI:$IMAGE_TAG .
          docker tag $REPO_URI:$IMAGE_TAG $REPO_URI:$IMAGE_TAG_WITH_DATE

      - name: Push Docker image to ECR
        run: |
          docker push $REPO_URI:$IMAGE_TAG
          docker push $REPO_URI:$IMAGE_TAG_WITH_DATE
